Create aim-for-stateless-design.md
Green-Software-Foundation/green-software-patterns pull request #145
Opened 2022-10-28 00:28 UTC by yelghali

@dubrie

2022-10-30 21:02 UTC, dubrie requested changes
@yelghali some minor changes requested from initial review

2022-10-30 21:02 UTC, dubrie commented on docs/catalog/cloud/aim-for-stateless-design.md
> +# Aim for stateless design
Use "implement" here instead of "aim": `Implement stateless designs`

2022-10-30 21:02 UTC, dubrie commented on docs/catalog/cloud/aim-for-stateless-design.md
> +- `E`: Rightsizing the compute VM increases its utilization, hence increasing energy efficiency.
nit: Put the `E` section before the `M` section.  We try to keep each E, I, M, and R reference in the same order they appear in the equation.

2022-10-30 22:18 UTC, yelghali commented
@dubrie . done, thank you

2022-10-30 22:51 UTC, dubrie commented
assigning to @dubrie for SME Review

2022-10-30 22:54 UTC, dubrie requested changes
SME review is good, some additional minor typo changes needed still

2022-10-30 22:54 UTC, dubrie commented on docs/catalog/cloud/implement-stateless-design.md
> +Applications that consumes large memory or on-disk data, require larger VM sizes, especially for cloud computing where you would need larger VM SKUs to support high RAM capacity and multiple data dis
typo: "Applications that consume"

2022-10-30 22:54 UTC, dubrie commented on docs/catalog/cloud/implement-stateless-design.md
> +State can be either externalized in a noSQL database or an in-memroy cache service.
typo: "in-memory"

2022-10-31 16:05 UTC, yelghali commented on docs/catalog/cloud/implement-stateless-design.md
> +Applications that consumes large memory or on-disk data, require larger VM sizes, especially for cloud computing where you would need larger VM SKUs to support high RAM capacity and multiple data dis
thks

2022-10-31 16:05 UTC, yelghali commented on docs/catalog/cloud/implement-stateless-design.md
> +State can be either externalized in a noSQL database or an in-memroy cache service.
thks

2022-10-31 23:58 UTC, dubrie approved these changes

2022-10-31 23:58 UTC, merged