evaluate-whether-to-use-TLS-termination.md
Green-Software-Foundation/green-software-patterns pull request #146
Opened 2022-10-28 00:59 UTC by yelghali

@dubrie

2022-10-30 21:07 UTC, dubrie requested changes
@yelghali some updates requested from initial review

2022-10-30 21:07 UTC, dubrie commented on docs/catalog/cloud/evaluate-whether-to-use-TLS-termination.md
> +- security
please include `cloud` in the list of tags

2022-10-30 21:07 UTC, dubrie commented on docs/catalog/cloud/evaluate-whether-to-use-TLS-termination.md
> +Consider if you can terminate TLS at your border gateway and continue with non-TLS to your application load balancer and onwards to your workload.
It seems like this should be a consideration on the pattern and the solution should focus more on the action of terminating TLS at the border gateway.

2022-10-30 21:07 UTC, dubrie commented on docs/catalog/cloud/evaluate-whether-to-use-TLS-termination.md
> +# Evaluate whether to use TLS termination
Consider changing to something like `Terminate TLS at border gateway`. We look for titles to be action-oriented on a resource and can move the discussion of whether or not you should (or can) to the assumptions and considerations sections.

2022-10-30 21:07 UTC, dubrie commented on docs/catalog/cloud/evaluate-whether-to-use-TLS-termination.md
> +- `E`: By reducing CPU utilization, we reduce the amount of energy needed to support the communication transport.
Did you mean CPU usage instead of CPU utilization? Reducing utilization typically is worse for emissions whereas requiring less CPU would be better.

2022-10-31 13:42 UTC, yelghali commented
@dubrie , thank you; done.

2022-10-31 23:37 UTC, dubrie commented
assigning to @dubrie for SME review

2022-10-31 23:41 UTC, dubrie requested changes
Minor updates, otherwise good!

2022-10-31 23:41 UTC, dubrie commented on docs/catalog/cloud/evaluate-whether-to-use-TLS-termination.md
> +- kubernetes
I'm not sure how this relates to kubernetes based on the pattern content below

2022-10-31 23:41 UTC, dubrie commented on docs/catalog/cloud/evaluate-whether-to-use-TLS-termination.md
> +, we reduce the amount of energy needed to support the communication transport.
nit: make this one line

2022-11-01 00:33 UTC, yelghali commented
@dubrie , thks ok. fixed the line

2022-11-01 03:22 UTC, dubrie approved these changes

2022-11-01 03:22 UTC, merged