scan-for-vulnerabilities.md
Green-Software-Foundation/green-software-patterns pull request #150
Opened 2022-10-28 02:40 UTC by yelghali

@dubrie

2022-10-30 21:35 UTC, dubrie requested changes
some changes requested from the initial review. Additionally, if this was copied from somewhere else on the web, please use the References section to link back to the original source for proper citation and linking

2022-10-30 21:35 UTC, dubrie commented on docs/catalog/cloud/scan-for-vulnerabilities.md
> +- security
please include `cloud` in the list of tags as well

2022-10-30 21:35 UTC, dubrie commented on docs/catalog/cloud/scan-for-vulnerabilities.md
> +Vulnerability scanning and EDR tools help minimize the window of opportunity for attackers and mitigate any potential malicious usage of resources.
Can you define what EDR stands for here?

2022-10-30 21:35 UTC, dubrie commented on docs/catalog/cloud/scan-for-vulnerabilities.md
> +Zero Trust security policy is implemented, which covers security controls for infrastructure, applications, data, networking, RBAC and devices.
can you define what RBAC stands for here?

2022-10-31 14:42 UTC, yelghali commented
ok

2022-10-31 23:54 UTC, dubrie approved these changes

2022-10-31 23:54 UTC, dubrie commented
Looks great, thank you!

2022-10-31 23:54 UTC, merged