Create Use cloud native network security tools and controls.md
Green-Software-Foundation/green-software-patterns pull request #156
Opened 2022-10-28 23:37 UTC by yelghali

@dubrie

2022-10-30 22:07 UTC, dubrie requested changes
@yelghali changes requested from the initial review

2022-10-30 22:07 UTC, dubrie commented on docs/catalog/cloud/Use cloud native network security tools and controls.md
> +- security
please include "cloud" and "network" to the list of tags as well.

2022-10-30 22:07 UTC, dubrie commented on docs/catalog/cloud/Use cloud native network security tools and controls.md
> +Network & Web Application Firewalls provide protection against OWASP top 10 attacks and load shedding bad bots. Using these capabilities helps remove unnecessary data transmission and reduces the bur
What does OWASP stand for in this context?

2022-10-30 22:07 UTC, dubrie commented on docs/catalog/cloud/Use cloud native network security tools and controls.md
> +Filter Ingress and Egress traffic at the source, to remove the unnecessary data transmissions.
How do you define an "unnecessary" data transmission?

2022-10-31 15:08 UTC, yelghali commented
@dubrie thank you ok

2022-10-31 23:56 UTC, dubrie approved these changes

2022-10-31 23:56 UTC, dubrie commented
Looks good, thank you!

2022-10-31 23:56 UTC, merged