adds pattern for minimizing deployed environments
Green-Software-Foundation/green-software-patterns pull request #26
Opened 2022-08-16 02:07 UTC by camcash17

A proposal for minimizing deployed environments as green patterns

2022-08-18 21:06 UTC, dubrie commented
assigning to @dubrie for SME Review

2022-09-25 16:42 UTC, ravikp commented
How about changing the title to "Repurpose the environments" instead of "Minimizing deployed environments"? Also include running automated performance tests in the night and doing functional testing in the environment in the morning? Just a thought.

2022-09-30 23:53 UTC, dubrie requested changes
One ask for update on this would be to align to the updated [Template.md file](https://github.com/Green-Software-Foundation/green-software-patterns/blob/dev/TEMPLATE.md). While this discussion was happening, we modified the template to include references and shift some of the items to a metadata section. It should be straight-forward but please let me know if there is any confusion on which data should go where in the new format.

2022-09-30 23:53 UTC, dubrie commented on docs/catalog/minimizing-deployed-environments.md
> +- `M`: By reducing the amount of nodes running on underlying machines, we reduce the total embodied carbon.
I think this should just focus on reducing the total number of machines and resources. Deployed environments don't typically reduce nodes but rather full machines/virtual machines.

2022-10-01 00:00 UTC, dubrie commented
> How about changing the title to "Repurpose the environments" instead of "Minimizing deployed environments"? Also include running automated performance tests in the night and doing functional testing in the environment in the morning? Just a thought.

I think the title of this is accurate for the content, the goal of this pattern is to reduce and minimize the environments that you deploy and use. However, I think the other two options to propose with running automated test in the night and doing functional testing in the morning are interesting as a separate pattern. Is there a connection to the SCI Impact that you see? I've opened a new issue to continue the discussion further on this: https://github.com/Green-Software-Foundation/green-software-patterns/issues/85

2022-10-10 00:46 UTC, dubrie commented
Pinging @camcash17 for updates and/or thoughts on the feedback.

2022-10-18 00:39 UTC, closed without merging