Create optimize-peak-cpu-utilization.md
Green-Software-Foundation/green-software-patterns pull request #86
Opened 2022-10-01 00:51 UTC by dubrie

2022-10-05 02:44 UTC, dubrie commented
Assigning to @srini1978 for SME Review in Cloud category

2022-10-11 11:26 UTC, srini1978 requested changes
1) Can we modify the pattern title to say both "Peak and Average" CPU utilization . This is because many auto scale out rules are built on Average CPU utilization and hence would like to include those cases as well. The same comment can be applied in all the verbiages used in the pattern solution
2) Can we call out some techniques that can help optimize peak CPU utilizations. The techniques may be design run time (loop considerations, Query optimizations) . You have covered that you are not looking for hardware additions in the "Considerations" section and hence we need to find out a way to call out some example techniques of reducing CPU utilization.
3) Another way to achieve comment #2 is to call out patterns that tend to reduce Peak CPU utilization . For example the patterns around "Reduce Transmitted data" and "queue non-urgent requests" as these are all patterns that reduce the CPU utilization of the core servers

2022-10-14 03:57 UTC, dubrie commented
> 1. Can we modify the pattern title to say both "Peak and Average" CPU utilization . This is because many auto scale out rules are built on Average CPU utilization and hence would like to include those cases as well. The same comment can be applied in all the verbiages used in the pattern solution
> 
>     2. Can we call out some techniques that can help optimize peak CPU utilizations. The techniques may be design run time (loop considerations, Query optimizations) . You have covered that you are not looking for hardware additions in the "Considerations" section and hence we need to find out a way to call out some example techniques of reducing CPU utilization.
> 
>     3. Another way to achieve comment #2 is to call out patterns that tend to reduce Peak CPU utilization . For example the patterns around "Reduce Transmitted data" and "queue non-urgent requests" as these are all patterns that reduce the CPU utilization of the core servers

Great suggestions, replies below:

1. The way we are building out patterns, that would be a 2nd pattern submitted for Average. Where possible we want to use the format of "Action on Resource". The content will likely be very similar between them but the approach is different. I added a 2nd pattern here to cover the average scenario
2. Sounds good, updates in the pattern(s)
3. Agreed, once we have a bigger set of patterns we can look for the cross-references. It's tricky now because some of the patterns haven't been formally added yet but when we go through the consistency review this will easier to align.

2022-10-18 08:36 UTC, srini1978 approved these changes

2022-10-18 13:23 UTC, merged